name: Test Action
on: [push] #배열로 씀

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Fetch the num's squared
        id: get_square
        uses: ./ # Uses an action in the root directory
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
